"""Created user model

Revision ID: 9e2c9ff242eb
Revises: 
Create Date: 2026-07-22 14:55:58.083593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2c9ff242eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('uuid', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('password', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('first_name', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.Column('last_name', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=True),
                    sa.Column('phone_number', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=True),
                    sa.Column('role', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('uuid', name=op.f('users_pkey')),
                    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[
                    ], postgresql_nulls_not_distinct=False)
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
