"""added parent email FK to child table

Revision ID: e563fbb27f53
Revises: 161f9996ef33
Create Date: 2026-08-01 15:03:23.409025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e563fbb27f53'
down_revision: Union[str, Sequence[str], None] = '161f9996ef33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('parent_email', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'children', 'users', ['parent_email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'children', type_='foreignkey')
    op.drop_column('children', 'parent_email')
    # ### end Alembic commands ###
